### ISSUE TITLE
Propose Logo/Icon

### ISSUE THREAD

**Issue by mirzazulfan** [tetzank/videojs-snapshot#5]
Hi @tetzank , I'm a graphic designer and an open source enthusiast. I've designed a logo for you. If you like it you can use it. If you need to make a change please let me know. Best Regard.
![video](https://user-images.githubusercontent.com/36124339/48340568-8034d480-e69d-11e8-990a-a52f96b2c7ca.png)

**Comment by tetzank** [comment]
Hi, I'm very sorry for the late reply.

Thank you very much for providing a logo. I'm not really sure where to use it and if such a small plugin even needs one. I guess, I will put at the top of the readme file for now.

What is the license of these images?

Best regards.

**Comment by mirzazulfan** [comment]
Hi @tetzank you can use it, its free. Best Regard
[FILES](https://drive.google.com/drive/folders/1jmRxMpP5700EqnUDQcq6-Svz5UhoWPQI)

#### License
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.

**Comment by tetzank** [comment]
I'm very sorry for the long delay. I added your logo to the readme and demo page. Thank you very much for your contribution.
